replicaCount: 2
image:
  repository: 465362303741.dkr.ecr.ap-south-1.amazonaws.com/django-ecommerce-platform
  tag: 36b08289b93fc7f6c60dbca721a06c11d6fb4def
service:
  port: 8000
resources:
  requests:
    cpu: 750m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
