replicaCount: 2
image:
  repository: 465362303741.dkr.ecr.ap-south-1.amazonaws.com/django-ecommerce-platform
  tag: ff87a871f49d74964088cc8d3ca42695c06c7f95
service:
  port: 8000
resources:
  requests:
    cpu: 750m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
