replicaCount: 2
image:
  repository: 465362303741.dkr.ecr.ap-south-1.amazonaws.com/django-ecommerce-platform
  tag: ef3723386888df6da28d8179dc3492b7e12e7bc1
service:
  port: 8000
resources:
  requests:
    cpu: 750m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
